name: Deploy Workflow
on:
  workflow_dispatch:
    inputs:
      deploy-environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
      image-tag:
        description: 'Docker tag to deploy'
        required: true
        default: 'latest'
env:
  # TODO: Change to name of your Docker Registry (eg. mck-team-name.jfrog.io)
  DOCKER_REGISTRY: "mck-ontada-sre.jfrog.io"
  IMAGE_TAG: "${{ github.event.inputs.image-tag }}"
  ENV: "${{ github.event.inputs.deploy-environment }}"

jobs:
  deploy:
     if: ${{ github.ref == 'refs/heads/main' }}
     runs-on: ubuntu-latest
      needs:
      - docker-build
     steps:
      - uses: actions/checkout@v3
      - name: Add Server key
        run: |
          touch key.txt && echo "${{ secrets.SERVER_KEY }}" > key.txt
          chmod 600 key.txt
      - name: Deploy the application
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          set -e
          ./deploy.sh

